--[[
                                G A D G E T S
      -----------------------------------------------------------------
                            wildtide@wildtide.net
                           DoomSprout: Rift Forums 
      -----------------------------------------------------------------
      Gadgets Framework   : v0.6.2
      Project Date (UTC)  : 2014-05-04T15:20:31Z
      File Modified (UTC) : 2013-01-04T22:17:01Z (Wildtide)
      -----------------------------------------------------------------     
--]]

-- DO NOT EDIT THIS FILE DIRECTLY. LOCALIZATION IS HANDLED USING CURSEFORGE LOCALIZATION
Library.Translate.Fr(
{
	AddGadget = "Ajouter Gadget",
	BuffSettings = "Paramètres de Buff", -- Needs review
	Cancel = "Annuler",
	CannotAlterGadgetsInCombat = "Modification de gadgets impossible en combat",
	Cleric = "Clerc",
	ClickThroughNote = "Soyez avisé, que due aux restrictions des API de Rift, activer les fonctionnalités de click dans les formes impliqueront que vous pourrez pas cliquer sur les unités dans le monde derrière ces formes, et ce même si elles sont visibles. Pour cette raison, la forme de Raid affichera un rectangle derrière les formes quand les click sont activés, en guise d'indice qu'il y a quelques choses sur le chemin!", -- Needs review
	CopyGadget = "Copie Gadget",
	CPUUsage = "Utilisation du processeur", -- Needs review
	Create = "Créer",
	CreateGadget = "Créer Gadget",
	DeleteGadget = "Effacer Gadget",
	EnableClickToTarget = "Activer clic sur cible", -- Needs review
	EnableContextMenu = "Activer menu contexte sur click droit",
	Energy = "Énergie",
	ExcludeBuffsNote = "Modèles qui supportent cette option ne créront pas de panneux de Buff si cette option est sélectionnée. Celà vous permet d'utiliser les Gadget Panneau de Buff à la place, qui vous donnera plus de flexibilité.", -- Needs review
	Gadget = "Gadget",
	gadgetChargeMeter_desc = "L'indicateur de Charge affiche vos charges actuelles. Utile uniquement pour les mages, ce gadget existe afin que la forme standard d'Unité n'est pas besoin de gérer de barre additionnelle avec cet outil.",
	gadgetChargeMeter_name = "Indicateur de Charge",
	gadgetChargeMeter_note = "L'indicateur de Charge affiche vos charges actuelles. Utile uniquement pour les mages, ce gadget existe afin que la forme standard d'Unité n'est pas besoin de gérer de barre additionnelle avec cet outil.",
	gadgetComboPoints_desc = "Combo ou Points d'Attaque",
	gadgetComboPoints_name = "Points de Combo",
	gadgetCPU_desc = "Afficher l'utilisation du processeur des Addons", -- Needs review
	gadgetCPU_name = "Moniteur CPU", -- Needs review
	gadgetFPS_desc = "Afficher Images par Seconde",
	gadgetFPS_name = "Moniteur IPS",
	gadgetPlanarCharge_desc = "Afficher Charge Planaire",
	gadgetPlanarCharge_name = "Charge Planaire",
	gadgetRaidFrames_desc = "Gadget de Portraits de Raid", -- Needs review
	gadgetRaidFrames_name = "Portraits de Raid", -- Needs review
	gadgetRangeFinder_desc = "Afficher Distance de la Cible",
	gadgetRangeFinder_name = "Découveur de Distance",
	gadgetReloadUI_desc = "Bouton Recharge UI", -- Needs review
	gadgetReloadUI_name = "Recharger UI", -- Needs review
	Gadgets = "Gadgets",
	gadgetSoulVitality_desc = "Afficher Vitalité d'Âme", -- Needs review
	gadgetSoulVitality_name = "Vitalité de l'Âme", -- Needs review
	gadgetUnitFrame_desc = "Gadget Portrait d'Unité", -- Needs review
	gadgetUnitFrame_name = "Portrait d'Unité", -- Needs review
	Health = "Santé",
	LockGadgets = "Figer Gadgets",
	Mage = "Mage",
	Mana = "Mana",
	Modify = "Modifier",
	ModifyGadget = "Modifier Gadget",
	ModifyMessage = "Modifier les options de configuration pour le gadget ci-dessous et cliquez sur Modifier", -- Needs review
	OK = "OK", -- Needs review
	Power = "Puissance",
	RaidFrameTemplate = "Modèle de Portrait de Raid", -- Needs review
	ReloadInterface = "Recharger Interface",
	ReloadUI = "Recharger UI",
	ReloadUIMessage = "SVP recharger l'interface usager pour relâcher les ressources allouées.",
	Rogue = "Voleur",
	SelectGadgetType = "Choisir Type Gadget",
	Settings = "Paramètres", -- Needs review
	TOTAL = "TOTAL",
	UnitFrameTemplate = "Modèle de portrait de l'unité", -- Needs review
	UnitToTrack = "Unité à Suivre", -- Needs review
	UnlockGadgets = "Déverrouiller Gadgets", -- Needs review
	Version = "Version",
	Warrior = "Guerrier",
	writtenBy = "écrit par",
}

)