--[[
                                G A D G E T S
      -----------------------------------------------------------------
                            wildtide@wildtide.net
                           DoomSprout: Rift Forums 
      -----------------------------------------------------------------
      Gadgets Framework   : v0.5.6
      Project Date (UTC)  : 2013-11-03T06:56:55Z
      File Modified (UTC) : 2013-09-23T07:04:27Z (lifeismystery)
      -----------------------------------------------------------------     
--]]

Library.Translate.En(
{
	AddGadget = "Add Gadget",
	Apply = "Apply",
	BuffBlackList = "Blacklisted Buffs",
	BuffSettings = "Buff Settings",
	Cancel = "Cancel",
	CannotAlterGadgetsInCombat = "Cannot alter gadgets in combat",
	Charge = "Charge",
	Cleric = "Cleric",
	ClickThroughNote = "Please be aware, due to restrictions in the Rift API, enabling click functionality for frames means you will not be able to click on units in the world behind the frames, even when they are invisible. For this reason, the Raid Frames will display a dim rectangle behind the frames when clicking is enabled, as a hint that there is something in the way!",
	CopyGadget = "Copy Gadget",
	CPUUsage = "CPU Usage",
	Create = "Create",
	CreateGadget = "Create Gadget",
	DeleteGadget = "Delete Gadget",
	EnableClickToTarget = "Enable click to target",
	EnableContextMenu = "Enable context menu on right click",
	Energy = "Energy",
	ExcludeBuffsNote = "Templates that support this option will not create any Buff panels if this option is selected. This allows you to use a seperate Buff panel gadget instead, which provides more flexibility.",
	Gadget = "Gadget",
	gadgetChargeMeter_desc = "Displays Mage's Charge",
	gadgetChargeMeter_name = "Charge Meter",
	gadgetChargeMeter_note = "The Charge Meter displays the current charge. Only useful for mages, this gadget exists so that a standard Unit Frame doesn't have to handle the extra bar within it's layout.",
	gadgetCastBar_name = "Cast Bar",
	gadgetCastBar_desc = "Displays Cast Bar",
	gadgetComboPoints_desc = "Combo or Attack Points",
	gadgetComboPoints_name = "Combo Points",
	gadgetCPU_desc = "Displays Addon CPU Usage",
	gadgetCPU_name = "CPU Monitor",
	gadgetFPS_desc = "Displays Frames per Second",
	gadgetFPS_name = "FPS Monitor",
	gadgetDataTextBar_name = "Data Text Bar", 
	gadgetDataTextBar_desc = "Displays Data Text Bar",
	gadgetStatTextBar_name = "Stat Text Bar", 
	gadgetStatTextBar_desc = "Displays player Stats Bar",
	gadgetCurrenciesTextBar_name = "Currencies Text Bar", 
	gadgetCurrenciesTextBar_desc = "Displays player Currencies Bar",	
	gadgetGroupFrames_desc = "Group Frames Gadget",
	gadgetGroupFrames_name = "Group Frames",
	gadgetPlanarCharge_desc = "Displays Planar Charge",
	gadgetPlanarCharge_name = "Planar Charge",
	gadgetRaidFrames_desc = "Raid Frames Gadget",
	gadgetRaidFrames_name = "Raid Frames",
	gadgetRangeFinder_desc = "Displays Range to Target",
	gadgetRangeFinder_name = "Range Finder",
	gadgetReloadUI_desc = "Reload UI Button",
	gadgetReloadUI_name = "Reload UI",
	Gadgets = "Gadgets",
	gadgetSoulVitality_desc = "Displays Soul Vitality",
	gadgetSoulVitality_name = "Soul Vitality",
	gadgetUnitFrame_desc = "Unit Frame Gadget",
	gadgetUnitFrame_name = "Unit Frame",
	Health = "Health",
	HideWhenNoTarget = "Hide When No Target Available",
	HideWhenNotCasting = "Hide When Not Casting",
	LockGadgets = "Lock Gadgets",
	Mage = "Mage",
	Mana = "Mana",
	Modify = "Modify",
	ModifyGadget = "Modify Gadget",
	ModifyMessage = "Alter the configuration options for this gadget below, and click Modify",
	OK = "OK",
	Power = "Power",
	RaidFrameTemplate = "Raid Frame Template",
	ReloadInterface = "Reload Interface",
	ReloadUI = "Reload UI",
	ReloadUIMessage = "Please reload the User Interface to release allocated resources.",
	ReloadWillBeRequired = "You will need to reload the User Interface to apply these changes.",
	ReverseGroups = "Reverse Group Sequence",
	ReverseUnits = "Reverse Unit Sequence",
	Rogue = "Rogue",
	SelectGadgetType = "Select Gadget Type",
	Settings = "Settings",
	ShowAbsorb = "Show Absorb Display",
	ShowBackground = "Show Background",
	ShowBackgroundNote = "Show a transparent background when no unit is available",
	ShowCastTime = "Show Cast Time",
	ShowTargetName = "Show Target Name",
	ShowTitle = "Show Title",
	Texture = "Texture",
	TextureNoInterrupt = "Uninterruptable Texture",
	TOTAL = "TOTAL",
	UnitFrameTemplate = "Unit Frame Template",
	UnitToTrack = "Unit to Track",
	UnlockGadgets = "Unlock Gadgets",
	Version = "Version",
	Warrior = "Warrior",
	writtenBy = "written by",
}
)