--[[
                                G A D G E T S
      -----------------------------------------------------------------
                            wildtide@wildtide.net
                           DoomSprout: Rift Forums 
      -----------------------------------------------------------------
      Gadgets Framework   : v0.6.2
      Project Date (UTC)  : 2014-05-04T15:20:31Z
      File Modified (UTC) : 2013-01-04T22:17:01Z (Wildtide)
      -----------------------------------------------------------------     
--]]

-- DO NOT EDIT THIS FILE DIRECTLY. LOCALIZATION IS HANDLED USING CURSEFORGE LOCALIZATION
Library.Translate.De(
{
	AddGadget = "Gadget hinzufügen", -- Needs review
	BuffSettings = "Einstellungen für Buffs", -- Needs review
	Cancel = "Abbrechen", -- Needs review
	CannotAlterGadgetsInCombat = "Gadgets können im Kampf nicht geändert werden", -- Needs review
	Cleric = "Kleriker", -- Needs review
	ClickThroughNote = "Bitte beachte, dass, aufgrund von Einschränkungen in der Rift API, du nicht in der Lage bist Einheiten in der Spielwelt anzuklicken, die sich hinter Frames befinden, für die Anklicken aktiviert wurde, auch wenn sie nicht angezeigt werden. Aufgrund dessen wird hinter Raid Frames, für die Anklicken aktiviert wurde, ein schwaches Rechteck angezeigt um anzudeuten, dass sich dort etwas befindet.", -- Needs review
	CopyGadget = "Gadget kopieren", -- Needs review
	CPUUsage = "CPU Auslastung", -- Needs review
	Create = "Erstellen", -- Needs review
	CreateGadget = "Gadget erzeugen", -- Needs review
	DeleteGadget = "Gadget löschen", -- Needs review
	EnableClickToTarget = "Durch anklicken ins Ziel nehmen aktivieren", -- Needs review
	EnableContextMenu = "Kontextmenü bei Rechtsklick aktivieren", -- Needs review
	Energy = "Energie", -- Needs review
	ExcludeBuffsNote = "Vorlagen, die diese Option unterstützen, werden keine Bufffelder anzeigen wenn diese Option aktiviert ist. Das ermöglicht es dir statt dessen ein anderes Gadget zu nutzen, welches mehr Flexibilität bietet.", -- Needs review
	Gadget = "Gadget", -- Needs review
	gadgetChargeMeter_desc = "Das Ladungsmeter zeigt die aktuelle Ladung an. Ist nur nützlich für Magier. Dieses Gadget existiert nur damit Standard-Einheitenframes keine Zusatzleiste in ihrem Layout handhaben müssen.", -- Needs review
	gadgetChargeMeter_name = "Ladungsmeter", -- Needs review
	gadgetChargeMeter_note = "Das Ladungsmeter zeigt die aktuelle Ladung an. Ist nur nützlich für Magier. Dieses Gadget existiert nur damit Standard-Einheitenframes keine Zusatzleiste in ihrem Layout handhaben müssen.", -- Needs review
	gadgetComboPoints_desc = "Zeigt Kombo- oder Angriffspunkte an", -- Needs review
	gadgetComboPoints_name = "Kombopunkte", -- Needs review
	gadgetCPU_desc = "Zeigt die CPU Auslastung von Addons", -- Needs review
	gadgetCPU_name = "CPU Monitor", -- Needs review
	gadgetFPS_desc = "Zeigt die Bildwiederholungsrate an", -- Needs review
	gadgetFPS_name = "FPS Monitor", -- Needs review
	gadgetPlanarCharge_desc = "Zeigt die Ebenenladungen an", -- Needs review
	gadgetPlanarCharge_name = "Ebenenladungen", -- Needs review
	gadgetRaidFrames_desc = "Gadget für Raidframes", -- Needs review
	gadgetRaidFrames_name = "Raidframes", -- Needs review
	gadgetRangeFinder_desc = "Zeigt die Entfernung zum Ziel an", -- Needs review
	gadgetRangeFinder_name = "Entfernungssucher", -- Needs review
	gadgetReloadUI_desc = "Button für das Neuladen der UI", -- Needs review
	gadgetReloadUI_name = "UI Neuladen", -- Needs review
	Gadgets = "Gadgets", -- Needs review
	gadgetSoulVitality_desc = "Zeigt die Seelenvitalität an", -- Needs review
	gadgetSoulVitality_name = "Seelenvitalität", -- Needs review
	gadgetUnitFrame_desc = "Gadget für Einheitenframes", -- Needs review
	gadgetUnitFrame_name = "Einheitenframe", -- Needs review
	Health = "Gesundheit", -- Needs review
	LockGadgets = "Gadgets sperren", -- Needs review
	Mage = "Magier", -- Needs review
	Mana = "Mana", -- Needs review
	Modify = "Ändern", -- Needs review
	ModifyGadget = "Gadget ändern", -- Needs review
	ModifyMessage = "Nachricht ändern", -- Needs review
	OK = "OK", -- Needs review
	Power = "Kraft", -- Needs review
	RaidFrameTemplate = "Raid Frame Vorlage", -- Needs review
	ReloadInterface = "Interface neuladen", -- Needs review
	ReloadUI = "UI neuladen", -- Needs review
	ReloadUIMessage = "Bitte lade das Benutzerinterface neu um belegte Ressourcen freizugeben.", -- Needs review
	Rogue = "Schurke", -- Needs review
	SelectGadgetType = "Gadgettyp auswählen", -- Needs review
	Settings = "Einstellungen", -- Needs review
	TOTAL = "TOTAL", -- Needs review
	UnitFrameTemplate = "Vorlage für Einheitenframes", -- Needs review
	UnitToTrack = "Angezeigte Einheit", -- Needs review
	UnlockGadgets = "Gadgets entsperren", -- Needs review
	Version = "Version", -- Needs review
	Warrior = "Krieger", -- Needs review
	writtenBy = "erstellt von", -- Needs review
}

)
