--[[
                                G A D G E T S
      -----------------------------------------------------------------
                            wildtide@wildtide.net
                           DoomSprout: Rift Forums 
      -----------------------------------------------------------------
      Gadgets Framework   : v0.6.2
      Project Date (UTC)  : 2014-05-04T15:20:31Z
      File Modified (UTC) : 2013-01-04T22:17:01Z (Wildtide)
      -----------------------------------------------------------------     
--]]

-- DO NOT EDIT THIS FILE DIRECTLY. LOCALIZATION IS HANDLED USING CURSEFORGE LOCALIZATION
Library.Translate.Ru(
{
	AddGadget = "Добавить Гаджет", -- Needs review
	BuffSettings = "Настройки Баффов", -- Needs review
	Cancel = "Отмена", -- Needs review
	CannotAlterGadgetsInCombat = "Не возможно добавить гаджет в бою", -- Needs review
	Cleric = "Клерик", -- Needs review
	CopyGadget = "Копировать гаджет", -- Needs review
	CPUUsage = "CPU монитор", -- Needs review
	Create = "Добавить", -- Needs review
	CreateGadget = "Создать гаджет", -- Needs review
	DeleteGadget = "Удалить гаджет", -- Needs review
	EnableClickToTarget = "Активировать нажатие по цели", -- Needs review
	EnableContextMenu = "Активировать меню", -- Needs review
	Energy = "Энергия", -- Needs review
	ExcludeBuffsNote = "Шаблон не создаёт панель баффов и дебаффов.", -- Needs review
	Gadget = "Гаджет", -- Needs review
	gadgetChargeMeter_desc = "Индикатор зарядов отображает кол-во зарядов. Предназначено только для магов, этот гаджет добавляет панель зарядов отдельно от стандартного фрейма.", -- Needs review
	gadgetChargeMeter_name = "Индикатор зарядов", -- Needs review
	gadgetChargeMeter_note = "Индикатор зарядов отображает кол-во зарядов. Предназначено только для магов, этот гаджет добавляет панель зарядов отдельно от стандартного фрейма.", -- Needs review
	gadgetComboPoints_desc = "Комбо и очки атаки", -- Needs review
	gadgetComboPoints_name = "Комбо очки", -- Needs review
	gadgetCPU_desc = "Отображение нагрузки CPU аддонами", -- Needs review
	gadgetCPU_name = "CPU монитор", -- Needs review
	gadgetFPS_desc = "Отображение FPS", -- Needs review
	gadgetFPS_name = "Fps монитор", -- Needs review
	gadgetPlanarCharge_desc = "Отображение планарных зарядов", -- Needs review
	gadgetPlanarCharge_name = "Планарные заряды", -- Needs review
	gadgetRaidFrames_desc = "Рейд фрейм Гаджет", -- Needs review
	gadgetRaidFrames_name = "Рейд Фрейм", -- Needs review
	gadgetRangeFinder_desc = "Отображение дистанции до цели", -- Needs review
	gadgetRangeFinder_name = "Линейка", -- Needs review
	gadgetReloadUI_desc = "Кнопка перезагрузки UI", -- Needs review
	gadgetReloadUI_name = "Перезагрузка UI", -- Needs review
	Gadgets = "Гаджеты", -- Needs review
	gadgetSoulVitality_desc = "Отображение состояния души", -- Needs review
	gadgetSoulVitality_name = "Состояние души", -- Needs review
	gadgetUnitFrame_desc = "Юнит фрейм гаджет", -- Needs review
	gadgetUnitFrame_name = "Юнит фрейм", -- Needs review
	Health = "Жизнь", -- Needs review
	LockGadgets = "Заблокировать гаджеты", -- Needs review
	Mage = "Маг", -- Needs review
	Mana = "Мана", -- Needs review
	Modify = "Модифицировать", -- Needs review
	ModifyGadget = "Модифицировать гаджет", -- Needs review
	ModifyMessage = "Модифицировать сообщение", -- Needs review
	OK = "Ок", -- Needs review
	Power = "Сила", -- Needs review
	RaidFrameTemplate = "Шаблон Рейд Фрейма", -- Needs review
	ReloadInterface = "Перезагрузка UI", -- Needs review
	ReloadUI = "Перезагрузка UI", -- Needs review
	ReloadUIMessage = "Пожалуйста перезагрузите UI для обновления изменений", -- Needs review
	Rogue = "Разбойник", -- Needs review
	SelectGadgetType = "Выбор типа Гаджета", -- Needs review
	Settings = "Настройки", -- Needs review
	TOTAL = "Общее", -- Needs review
	UnitFrameTemplate = "Шаблон Unit фрейма", -- Needs review
	UnitToTrack = "Отслеживание", -- Needs review
	UnlockGadgets = "Разблокировать Гаджеты", -- Needs review
	Version = "Версия", -- Needs review
	Warrior = "Воин", -- Needs review
	writtenBy = "Написан by", -- Needs review
}

)
