--[[
                                G A D G E T S
      -----------------------------------------------------------------
                            wildtide@wildtide.net
                           DoomSprout: Rift Forums 
      -----------------------------------------------------------------
      Gadgets Framework   : v0.6.2
      Project Date (UTC)  : 2014-05-04T15:20:31Z
      File Modified (UTC) : 2013-01-04T22:17:01Z (Wildtide)
      -----------------------------------------------------------------     
--]]

-- DO NOT EDIT THIS FILE DIRECTLY. LOCALIZATION IS HANDLED USING CURSEFORGE LOCALIZATION
Library.Translate.Ko(
{
}

)
